app/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('main', views.index, name='index'),
    path('hot/', views.hot, name='hot'),
    path('question/<int:question_id>', views.question, name='question'),
    path('ask', views.ask, name='ask'),
    path('login/', views.login, name='login'),
    path('settings', views.settings, name='settings'),
    path('signup', views.signup, name='signup'),
    path('tag/', views.tag, name='all_tags'), 
    path('users', views.users, name='users'), 
    path('logout/', views.logout, name='logout'),
    path('tag/<str:tag_name>/', views.tag, name='questions_by_tag'),
    path('question/<int:question_id>/like/', views.like_question, name='like_question'),
    path('answer/<int:answer_id>/like/', views.like_answer, name='like_answer'),
    path('answer/<int:answer_id>/mark_correct/', views.mark_answer_correct, name='mark_answer_correct')
    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ask_pupkin_mokhammed/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete, m2m_changed
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)

    def __str__(self):
        return self.user.username
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.name

class QuestionManager(models.Manager):
    def new(self):
        return self.order_by('-created_at')
    
    def best(self):
        return self.annotate(likes_count=models.Count('questionlike')).order_by('-likes_count')

class Question(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    objects = QuestionManager()
    tags = models.ManyToManyField(Tag, related_name='questions')
    def save(self, *args, **kwargs):
        if not self.pk:  # Для нового вопроса
            self.rating = 0
        super().save(*args, **kwargs)

class Answer(models.Model):
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    is_correct = models.BooleanField(default=False)
    rating = models.IntegerField(default=0)
class QuestionLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = ('user', 'question')

class AnswerLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = ('user', 'answer')
@receiver([post_save, post_delete], sender=QuestionLike)
def update_question_rating(sender, instance, **kwargs):
    question = instance.question
    new_rating = QuestionLike.objects.filter(question=question).count()
    Question.objects.filter(pk=question.pk).update(rating=new_rating)
@receiver([post_save, post_delete], sender=AnswerLike)
def update_answer_rating(sender, instance, **kwargs):
    answer = instance.answer
    answer.rating = AnswerLike.objects.filter(answer=answer).count()
    answer.save()
print("Все гуд")

templates/components/answers.html
{% load static %}
<div class="card mb-4 mt-3" data-search ="msg-template" style="width: 100%;">
    <div class="card-body">
        <div class="d-flex">
            <div class="col-1 me-3">
                <div style="height: 65px;" class="border rounded mb-2 w-100">
                    {% if answer.author.profile.avatar %}
                        <img src="{{ answer.author.profile.avatar.url }}" alt="avatar" class="img-fluid h-100 w-100 object-fit-cover">
                    {% else %}
                        <img src="{% static 'img/default_avatar.png' %}" alt="avatar" class="img-fluid h-100 w-100 object-fit-cover">
                    {% endif %}
                </div>
                <form method="post" action="{% url 'like_answer' answer.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-primary">
                        <i class="bi bi-heart"></i> 
                        <span class="like-count">{{ answer.answerlike_set.count }}</span>
                    </button>
                </form>
            </div>
            <div class="col-11 d-flex flex-column">
                <p class="card-text" data-search="msg-content">{{ answer.content }}</p>
                <div class="form-check">
                    <input class="form-check-input mark-correct-checkbox" 
                           type="checkbox" 
                           data-answer-id="{{ answer.id }}"
                           {% if answer.is_correct %}checked{% endif %}
                           {% if request.user != answer.question.author %}disabled{% endif %}>
                    <label class="form-check-label" for="flexCheckChecked">
                        <div class="fw-semibold">Correct!</div>
                    </label>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/pagination.html
{% load static %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item mb-5 {% if not questions.has_previous %}disabled{% endif %}">
            <a class="page-link" 
               href="{% if questions.has_previous %}?page={{ questions.previous_page_number }}{% else %}#{% endif %}" 
               aria-label="Previous">
                &laquo;
            </a>
        </li>
        {% for num in page_range %}
            <li class="page-item {% if num == questions.number %}active{% endif %}">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
        {% endfor %}
        <li class="page-item {% if not questions.has_next %}disabled{% endif %}">
            <a class="page-link" 
               href="{% if questions.has_next %}?page={{ questions.next_page_number }}{% else %}#{% endif %}" 
               aria-label="Next">
                &raquo;
            </a>
        </li>
    </ul>
  </nav>

templates/components/question-item.html
{% load static %}
<div class="card mb-4" style="width: 100%;">
    <div class="card-body">
        <div class="d-flex">
            <div class="col-1 me-3">
                <div style="height: 70px;" class="border rounded mb-2 w-100">
                    {% if question.author.profile.avatar %}
                    <img src="{{ question.author.profile.avatar.url }}" alt="Profile photo" class="img-fluid h-100 w-100 object-fit-cover">
                    {% else %}
                    <img src="{% static 'img/default_avatar.png' %}" alt="Default photo" class="img-fluid h-100 w-100 object-fit-cover">
                    {% endif %}
                </div>
                    <div>
                        <button type="submit" class="btn btn-outline-primary like-button" data-question-id="{{ question.id }}">
                            <i class="bi bi-heart"></i>
                            <span class="like-count">
                                {{ question.rating }}
                            </span>
                        </button>
                    </div>
            </div>
            <div class="col-11">
                <a href="{% url 'question' question.id %}"><h5 class="card-title">{{ question.title }}</h5></a>
                <p class="card-text mb-3">{{ question.content|truncatewords:35 }}</p>
                <a href="{% url 'question' question.id %}" class="card-link" style="margin-right: 30px;">
                    Answers ({{ question.answer_set.count }})
                </a>
                <span class="text-decoration-underline">Tags:</span>
                {% for tag in question.tags.all %}
                <a href="{% url 'questions_by_tag' tag_name=tag.name %}">
                    <span class="badge rounded-pill text-bg-primary font-monospace">{{ tag.name }}</span>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

templates/components/script.html
<script>
    const likeButtons = document.querySelectorAll('.like-button');
    likeButtons.forEach(button => {
        button.addEventListener('click', function(e) {
            const questionId = this.getAttribute('data-question-id');
            console.log('Liked question:', questionId);
        });
    });
</script>